services:
  light_messages_backend:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        ENVIRONMENT: local
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .envs/local/.django.env
      - .envs/local/.postgresql.env
    depends_on:
      - postgres
    command: /start.sh
    networks:
      - backend

  postgres:
    image: postgres:16.2-bookworm
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .envs/local/.postgresql.env
    networks:
      - backend

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - backend

  nginx:
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .envs/local/.nginx.env
    ports:
      - "80:80"
    depends_on:
      - light_messages_backend
    networks:
      - backend  # Add this line to connect nginx to the backend network

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume: