apiVersion: apps/v1
kind: Deployment
metadata:
  name: light-messages-channels
  labels:
    app: light-messages-channels
spec:
  replicas: 1
  selector:
    matchLabels:
      app: light-messages-channels
  template:
    metadata:
      labels:
        app: light-messages-channels
    spec:
      containers:
        - name: backend-channels
          image: abdelslam1997/light_messages_backend:latest
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: SERVICE_TYPE
              value: "channel"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name