apiVersion: apps/v1
kind: Deployment
metadata:
  name: light-messages-channels
spec:
  template:
    spec:
      containers:
        - name: backend-channels
          command: ["/bin/sh", "-c", "/start.sh"]
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: backend-secret
