apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: light-messages-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /api/v1/
            pathType: Prefix
            backend:
              service:
                name: backend-service-web
                port:
                  number: 8000
          - path: /ws/
            pathType: Prefix
            backend:
              service:
                name: channels-service
                port:
                  number: 8000
          - path: /admin/
            pathType: Prefix
            backend:
              service:
                name: backend-service-web
                port:
                  number: 8000
          - path: /static/
            pathType: Prefix
            backend:
              service:
                name: static-file-server
                port:
                  number: 80
          - path: /media/
            pathType: Prefix
            backend:
              service:
                name: static-file-server
                port:
                  number: 80