apiVersion: v1
kind: Service
metadata:
  name: static-file-server
  labels:
    app: static-file-server
spec:
  type: ClusterIP
  selector:
    app: static-file-server
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP